version: '3.8'

services:
  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-talker-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/pdf-talker
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=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
      - CHROMA_URL=http://chromadb:8000
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      chromadb:
        condition: service_healthy
    networks:
      - pdf-talker-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB service
  mongodb:
    image: mongo:6
    container_name: pdf-talker-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - pdf-talker-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Neo4j service
  neo4j:
    image: neo4j:5
    container_name: pdf-talker-neo4j
    restart: always
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    networks:
      - pdf-talker-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # ChromaDB service
  chromadb:
    image: chromadb/chroma:latest
    container_name: pdf-talker-chromadb
    restart: always
    volumes:
      - chromadb-data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - pdf-talker-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

# Define volumes for persistent data
volumes:
  mongodb-data:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
  chromadb-data:

# Define network
networks:
  pdf-talker-network:
    driver: bridge 